#!/bin/csh

limit descriptors 256

set DIR=/mud/home/sneezy/sun

set LIB=$DIR/lib
set CRASH=$DIR/crash
set TINYNEXT=$LIB/tinyworld.next
set TINYOLD=$LIB/tinyworld.old
set AREAS=$LIB/areas

set DATE=`/bin/date "+%m%d%y.%H%M"`
set theLine = `ps -x|egrep 'dmserver 7900|dbx |mv ' | grep -v grep | wc -l`

if ( $theLine == 0 ) then
  if ( -f $DIR/dmserver.next ) then 
    mv $DIR/dmserver $DIR/dmserver.old
    mv $DIR/dmserver.next $DIR/dmserver
  endif

  if ( -f $LIB/core ) then
    mv $LIB/core $CRASH/core.$DATE
  endif

  /bin/rm -f log

  if ( -f $DIR/log.err ) then
    mv $DIR/log.err $CRASH/log$DATE
  endif

  foreach FILE ( `ls $TINYNEXT` )
    mv $LIB/$FILE $TINYOLD/$FILE
    mv $TINYNEXT/$FILE $LIB/$FILE
  end

  foreach FILE ( `ls ${AREAS}.next` )
    mv $AREAS/$FILE $AREAS/${FILE}.bkp
    mv ${AREAS}.next/$FILE $AREAS/$FILE
  end

  ccn_7900 &

#  if ( -f LogWatcher.pid ) then
#    kill `cat LogWatcher.pid`
#  endif
#  ./LogWatcher &

endif

sleep 15

exec rebooter
