name: Build with CMake
inputs:
  preset:
    description: CMake preset to use
    required: false
    default: release-gcc
runs:
  using: composite
  steps:
    - name: Configure ccache
      shell: bash
      run: |
        ccache --set-config=max_size=500M
        ccache --set-config=compression=true
        ccache --zero-stats

    - name: Configure
      shell: bash
      env:
        PRESET: ${{ inputs.preset }}
      run: cmake --preset "${PRESET}"

    - name: Build
      shell: bash
      env:
        PRESET: ${{ inputs.preset }}
      run: cmake --build --preset "${PRESET}"

    - name: Show ccache stats
      shell: bash
      if: always()
      run: ccache --show-stats
