# hey emacs, this is -*- python -*-

Import(['env', 'libs'])


env.CxxTest('Pfile.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('Fruit.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('DBTest.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('CommTest.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('SString.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('Exceptions.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('ConvertTo.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('GarbleTest.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('Act.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('Tell.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('Cast.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('Stat.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
env.CxxTest('ConfigFile.h', LIBS=libs, CXXTEST_SKIP_ERRORS=False)
