# hey emacs, this is -*- python -*- vim: ft=python

Import(['env', 'libs'])

external_libs = [
    'crypt',
    'gtest',
    'gtest_main',
    'boost_program_options',
    'boost_regex',
    'boost_filesystem',
    'boost_system',
]

env.Append(CXXFLAGS=[
    '-Wno-unused-result',
    ])

env.Append(LIBPATH='../../objs')  # for libsneezy
libs = ['libsneezy'] + env.get('extra_libs', []) + external_libs + env.get('LIBS')

tests = env.Program(target='tests', source=Glob('test_*.cc'), LIBS=libs)
test_alias = env.Alias('tests', [tests], tests[0].abspath)
env.AlwaysBuild(test_alias)
