# hey emacs, this is -*- python -*- vim: ft=python

Import(['env', 'libs'])

env.Append(CXXFLAGS=[
    '-Wno-unused-result',
    ])

cxx_tests = (
        'Run',
        'Act',
        'CommTest',
        # 'Tell', disabled as it requires better mocking of DB than available now
        'Exceptions',
        'GarbleTest',
        'Pfile',
        'SString',
        'ConfigFile',
        'ConvertTo',
        'DBTest',
        'Fruit',
        'Stat',
)

for test in cxx_tests:
    env.CxxTest(test, CXXTEST_SUFFIX='.h', LIBS=libs,
                CXXTEST_SKIP_ERRORS=False)
