/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;
DROP TABLE IF EXISTS `mail`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `mail` (
  `mailid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `port` int(11) DEFAULT NULL,
  `mailfrom` varchar(80) DEFAULT NULL,
  `timesent` timestamp NULL DEFAULT NULL,
  `content` varchar(4000) DEFAULT NULL,
  `talens` int(11) DEFAULT 0,
  `rent_id` int(11) DEFAULT NULL,
  `to_id` bigint(20) unsigned NOT NULL,
  `from_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`mailid`),
  KEY `fk_mail_rent_id` (`rent_id`),
  KEY `idx_mail_to` (`to_id`,`port`),
  KEY `fk_mail_from_id` (`from_id`),
  CONSTRAINT `fk_mail_from_id` FOREIGN KEY (`from_id`) REFERENCES `player` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_mail_rent_id` FOREIGN KEY (`rent_id`) REFERENCES `rent` (`rent_id`) ON DELETE SET NULL,
  CONSTRAINT `fk_mail_to_id` FOREIGN KEY (`to_id`) REFERENCES `player` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

