/*M!999999\- enable the sandbox mode */ 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;
DROP TABLE IF EXISTS `shopownedcorpbank`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `shopownedcorpbank` (
  `shop_nr` int(11) NOT NULL,
  `corp_id` bigint(20) unsigned NOT NULL,
  `talens` int(11) DEFAULT NULL,
  `earned_interest` double DEFAULT NULL,
  PRIMARY KEY (`shop_nr`,`corp_id`),
  KEY `fk_shopownedcorpbank_corp_id` (`corp_id`),
  CONSTRAINT `fk_shopownedcorpbank_corp_id` FOREIGN KEY (`corp_id`) REFERENCES `corporation` (`corp_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_shopownedcorpbank_shop_nr` FOREIGN KEY (`shop_nr`) REFERENCES `shopowned` (`shop_nr`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
LOCK TABLES `shopownedcorpbank` WRITE;
/*!40000 ALTER TABLE `shopownedcorpbank` DISABLE KEYS */;
INSERT INTO `shopownedcorpbank` VALUES
(4,1,0,0),
(4,10,0,0),
(4,16,0,0),
(4,21,0,0),
(140,23,0,0),
(140,29,0,0),
(141,24,0,0),
(141,28,0,0),
(142,25,0,0),
(142,27,0,0);
/*!40000 ALTER TABLE `shopownedcorpbank` ENABLE KEYS */;
UNLOCK TABLES;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

