create table mob (
  vnum int primary key not null,
  name char(127) not null,
  short_desc char(127) not null,
  long_desc char(255) not null,
  description text not null,
  actions int not null,
  affects int not null,
  faction int not null,
  fact_perc float not null,
  letter char(1) not null,
  attacks float not null,
  class int not null,
  level int not null,
  tohit int not null,
  ac float not null,
  hpbonus float not null,
  damage_level float not null,
  damage_precision float not null,
  gold int not null,
  race int not null,
  weight int not null,
  height int not null,
  str int not null, 
  bra int not null, 
  con int not null, 
  dex int not null, 
  agi int not null, 
  intel int not null, 
  wis int not null, 
  foc int not null, 
  per int not null, 
  cha int not null, 
  kar int not null, 
  spe int not null,  
  def_position int not null,
  pos int not null,
  sex int not null,
  spec_proc int not null,
  skin int not null,
  vision int not null,
  can_be_seen int not null,
  max_exist int not null,
  local_sound char(127),
  adjacent_sound char(127)
);

create table mob_imm (
  vnum int,
  type int,
  amt int
);
