CREATE TABLE shop (
    shop_nr integer DEFAULT '0' NOT NULL,
    profit_buy double precision DEFAULT '0.00' NOT NULL,
    profit_sell double precision DEFAULT '0.00' NOT NULL,
    no_such_item1 varchar(127) DEFAULT '' NOT NULL,
    no_such_item2 varchar(127) DEFAULT '' NOT NULL,
    do_not_buy varchar(127) DEFAULT '' NOT NULL,
    missing_cash1 varchar(127) DEFAULT '' NOT NULL,
    missing_cash2 varchar(127) DEFAULT '' NOT NULL,
    message_buy varchar(127) DEFAULT '' NOT NULL,
    message_sell varchar(127) DEFAULT '' NOT NULL,
    temper1 integer DEFAULT '0' NOT NULL,
    temper2 integer DEFAULT '0' NOT NULL,
    keeper integer DEFAULT '0' NOT NULL,
    flags integer DEFAULT '0' NOT NULL,
    in_room integer DEFAULT '0' NOT NULL,
    open1 integer DEFAULT '0' NOT NULL,
    close1 integer DEFAULT '0' NOT NULL,
    open2 integer DEFAULT '0' NOT NULL,
    close2 integer DEFAULT '0' NOT NULL,
    expense_ratio double precision
);
