CREATE TABLE `mob` (
  `owner` varchar(80) NOT NULL,
  `vnum` int(11) NOT NULL,
  `name` char(127) NOT NULL,
  `short_desc` char(127) NOT NULL,
  `long_desc` char(255) NOT NULL,
  `description` text NOT NULL,
  `actions` int(11) UNSIGNED NOT NULL,
  `affects` int(11) UNSIGNED NOT NULL,
  `faction` int(11) NOT NULL,
  `fact_perc` int(11) NOT NULL,
  `letter` char(1) NOT NULL,
  `attacks` float(5, 1) NOT NULL,
  `class` int(11) NOT NULL,
  `level` int(11) NOT NULL,
  `tohit` int(11) NOT NULL,
  `ac` float(5, 1) NOT NULL,
  `hpbonus` float(5, 1) NOT NULL,
  `damage_level` float(5, 1) NOT NULL,
  `damage_precision` int(11) NOT NULL,
  `gold` int(11) NOT NULL,
  `race` int(11) NOT NULL,
  `weight` int(11) NOT NULL,
  `height` int(11) NOT NULL,
  `str` int(11) NOT NULL,
  `bra` int(11) NOT NULL,
  `con` int(11) NOT NULL,
  `dex` int(11) NOT NULL,
  `agi` int(11) NOT NULL,
  `intel` int(11) NOT NULL,
  `wis` int(11) NOT NULL,
  `foc` int(11) NOT NULL,
  `per` int(11) NOT NULL,
  `cha` int(11) NOT NULL,
  `kar` int(11) NOT NULL,
  `spe` int(11) NOT NULL,
  `pos` int(11) NOT NULL,
  `def_position` int(11) NOT NULL,
  `sex` int(11) NOT NULL,
  `spec_proc` int(11) NOT NULL,
  `skin` int(11) NOT NULL,
  `vision` int(11) NOT NULL,
  `can_be_seen` int(11) NOT NULL,
  `max_exist` int(11) NOT NULL,
  `local_sound` char(255) default NULL,
  `adjacent_sound` char(255) default NULL,
  PRIMARY KEY  (`owner`, `vnum`)
);
