-- MySQL dump 10.16  Distrib 10.1.28-MariaDB, for Linux (x86_64)
--
-- Host: localhost    Database: sneezy
-- ------------------------------------------------------
-- Server version	10.1.28-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `shop`
--

DROP TABLE IF EXISTS `shop`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `shop` (
  `shop_nr` int(11) NOT NULL DEFAULT '0',
  `profit_buy` double NOT NULL DEFAULT '0',
  `profit_sell` double NOT NULL DEFAULT '0',
  `no_such_item1` varchar(127) NOT NULL DEFAULT '',
  `no_such_item2` varchar(127) NOT NULL DEFAULT '',
  `do_not_buy` varchar(127) NOT NULL DEFAULT '',
  `missing_cash1` varchar(127) NOT NULL DEFAULT '',
  `missing_cash2` varchar(127) NOT NULL DEFAULT '',
  `message_buy` varchar(127) NOT NULL DEFAULT '',
  `message_sell` varchar(127) NOT NULL DEFAULT '',
  `temper1` int(11) NOT NULL DEFAULT '0',
  `temper2` int(11) NOT NULL DEFAULT '0',
  `keeper` int(11) NOT NULL DEFAULT '0',
  `flags` int(11) NOT NULL DEFAULT '0',
  `in_room` int(11) NOT NULL DEFAULT '0',
  `open1` int(11) NOT NULL DEFAULT '0',
  `close1` int(11) NOT NULL DEFAULT '0',
  `open2` int(11) NOT NULL DEFAULT '0',
  `close2` int(11) NOT NULL DEFAULT '0',
  `expense_ratio` double DEFAULT NULL,
  PRIMARY KEY (`shop_nr`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `shop`
--

LOCK TABLES `shop` WRITE;
/*!40000 ALTER TABLE `shop` DISABLE KEYS */;
INSERT INTO `shop` VALUES (0,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,150,0,559,0,96,0,0,0);
INSERT INTO `shop` VALUES (1,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','I only buy light!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,151,0,550,0,96,0,0,0);
INSERT INTO `shop` VALUES (2,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,152,0,555,0,96,0,0,0);
INSERT INTO `shop` VALUES (3,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,153,0,560,0,96,0,0,0);
INSERT INTO `shop` VALUES (4,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31765,0,31750,0,96,0,0,0);
INSERT INTO `shop` VALUES (5,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,155,0,561,0,96,0,0,0);
INSERT INTO `shop` VALUES (6,1.1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,156,0,508,0,96,0,0,0);
INSERT INTO `shop` VALUES (7,1.1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,157,0,506,0,96,0,0,0);
INSERT INTO `shop` VALUES (8,1.4,0.6,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,158,0,552,0,96,0,0,0);
INSERT INTO `shop` VALUES (9,1.2,0.6,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,159,0,562,0,96,0,0,0);
INSERT INTO `shop` VALUES (10,1.2,0.8,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,160,0,551,0,96,0,0,0);
INSERT INTO `shop` VALUES (11,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,161,0,646,0,96,0,0,0);
INSERT INTO `shop` VALUES (12,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,162,0,554,0,96,0,0,0);
INSERT INTO `shop` VALUES (13,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,19011,0,19011,0,96,0,0,0);
INSERT INTO `shop` VALUES (14,0.05,0,'','','','','','','',0,0,31766,0,31789,0,0,0,0,0);
INSERT INTO `shop` VALUES (15,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,165,0,558,0,96,0,0,0);
INSERT INTO `shop` VALUES (16,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8755,0,8755,0,96,0,0,0);
INSERT INTO `shop` VALUES (17,1,0.8,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4303,0,4368,0,96,0,0,0);
INSERT INTO `shop` VALUES (18,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1346,0,1346,0,96,0,0,0);
INSERT INTO `shop` VALUES (19,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1362,0,1362,0,96,0,0,0);
INSERT INTO `shop` VALUES (20,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1363,0,1363,0,96,0,0,0);
INSERT INTO `shop` VALUES (21,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1366,0,1366,0,96,0,0,0);
INSERT INTO `shop` VALUES (22,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1367,0,1367,0,96,0,0,0);
INSERT INTO `shop` VALUES (23,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1336,0,1336,0,96,0,0,0);
INSERT INTO `shop` VALUES (24,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1344,0,1344,0,96,0,0,0);
INSERT INTO `shop` VALUES (25,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,7515,0,7548,0,96,0,0,0);
INSERT INTO `shop` VALUES (26,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3727,0,3727,0,96,0,0,0);
INSERT INTO `shop` VALUES (27,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3728,0,3728,0,96,0,0,0);
INSERT INTO `shop` VALUES (28,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3741,0,3741,0,96,0,0,0);
INSERT INTO `shop` VALUES (29,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4504,0,4504,0,96,0,0,0);
INSERT INTO `shop` VALUES (30,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3743,0,3743,0,96,0,0,0);
INSERT INTO `shop` VALUES (31,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3770,0,3770,0,96,0,0,0);
INSERT INTO `shop` VALUES (32,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3859,0,3859,0,96,0,0,0);
INSERT INTO `shop` VALUES (33,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3860,0,3860,0,96,0,0,0);
INSERT INTO `shop` VALUES (34,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8735,0,8735,0,96,0,0,0);
INSERT INTO `shop` VALUES (35,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','You call that a weapon?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8728,0,8728,0,96,0,0,0);
INSERT INTO `shop` VALUES (36,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,167,0,568,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (37,1,0.2,'I don\'t have that right now.  Try \"list\".','What kind of a guppy do you think I am!','Go sell it to someone who cares!','Sorry, I have run out of clams!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14249,0,14249,0,96,0,0,0);
INSERT INTO `shop` VALUES (38,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14255,0,14255,0,96,0,0,0);
INSERT INTO `shop` VALUES (39,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,23635,0,23663,0,96,0,0,0);
INSERT INTO `shop` VALUES (40,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,23636,0,23665,0,96,0,0,0);
INSERT INTO `shop` VALUES (41,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,23637,0,23664,0,96,0,0,0);
INSERT INTO `shop` VALUES (42,0.1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,20000,0,20000,0,96,0,0,0);
INSERT INTO `shop` VALUES (43,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6837,0,6956,0,96,0,0,0);
INSERT INTO `shop` VALUES (44,1.2,0.8,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6836,0,6951,0,96,0,0,0);
INSERT INTO `shop` VALUES (45,1.2,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5735,0,5853,0,96,0,0,0);
INSERT INTO `shop` VALUES (46,1.2,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5713,0,5759,0,96,0,0,0);
INSERT INTO `shop` VALUES (47,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5714,0,5761,0,96,0,0,0);
INSERT INTO `shop` VALUES (48,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5736,0,5850,0,96,0,0,0);
INSERT INTO `shop` VALUES (49,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14326,0,14372,24,80,0,0,0);
INSERT INTO `shop` VALUES (50,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14324,0,14377,0,8,40,96,0);
INSERT INTO `shop` VALUES (51,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14325,0,14378,0,8,48,96,0);
INSERT INTO `shop` VALUES (52,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,11028,0,11027,0,96,0,0,0);
INSERT INTO `shop` VALUES (53,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,11033,0,11039,0,96,0,0,0);
INSERT INTO `shop` VALUES (54,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,11030,0,11033,0,96,0,0,0);
INSERT INTO `shop` VALUES (55,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,11029,0,11030,0,96,0,0,0);
INSERT INTO `shop` VALUES (56,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8734,0,8734,0,96,0,0,0);
INSERT INTO `shop` VALUES (57,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1393,0,1393,0,96,0,0,0);
INSERT INTO `shop` VALUES (58,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3709,0,3709,0,96,0,0,0);
INSERT INTO `shop` VALUES (59,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8797,0,8797,0,96,0,0,0);
INSERT INTO `shop` VALUES (60,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14332,0,14385,32,96,0,0,0);
INSERT INTO `shop` VALUES (61,1.2,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,11031,0,11029,0,96,0,0,0);
INSERT INTO `shop` VALUES (62,1.2,0.8,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1296,0,1296,0,96,0,0,0);
INSERT INTO `shop` VALUES (63,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','I\'m not really interested in buying that.','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5586,0,5586,0,96,0,0,0);
INSERT INTO `shop` VALUES (64,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5378,0,5378,0,96,0,0,0);
INSERT INTO `shop` VALUES (65,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,7002,0,7042,0,96,0,0,0);
INSERT INTO `shop` VALUES (66,1.1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,7003,0,7037,0,96,0,0,0);
INSERT INTO `shop` VALUES (67,1,0.2,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,7004,0,7043,0,96,0,0,0);
INSERT INTO `shop` VALUES (68,1.1,0.7,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16204,0,16201,0,96,0,0,0);
INSERT INTO `shop` VALUES (69,1.2,0.8,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8739,0,8739,0,96,0,0,0);
INSERT INTO `shop` VALUES (70,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8727,0,8727,0,96,0,0,0);
INSERT INTO `shop` VALUES (71,1.3,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8841,0,8841,0,96,0,0,0);
INSERT INTO `shop` VALUES (72,1.4,0.6,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8861,0,8861,0,96,0,0,0);
INSERT INTO `shop` VALUES (73,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,551,0,565,0,96,0,0,0);
INSERT INTO `shop` VALUES (74,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8798,0,8798,0,96,0,0,0);
INSERT INTO `shop` VALUES (75,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16107,0,16144,0,96,0,0,0);
INSERT INTO `shop` VALUES (76,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16106,0,16142,0,96,0,0,0);
INSERT INTO `shop` VALUES (77,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14250,0,14250,0,96,0,0,0);
INSERT INTO `shop` VALUES (78,1.3,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14265,0,14265,0,96,0,0,0);
INSERT INTO `shop` VALUES (79,2,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25525,0,25581,0,96,0,0,0);
INSERT INTO `shop` VALUES (80,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25526,0,25582,0,96,0,0,0);
INSERT INTO `shop` VALUES (81,1.5,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25528,0,25585,0,96,0,0,0);
INSERT INTO `shop` VALUES (82,1.5,0.6,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25530,0,25592,0,96,0,0,0);
INSERT INTO `shop` VALUES (83,1.5,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25531,0,25589,0,96,0,0,0);
INSERT INTO `shop` VALUES (84,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12234,0,12234,0,96,0,0,0);
INSERT INTO `shop` VALUES (85,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12236,2,12236,0,96,0,0,0);
INSERT INTO `shop` VALUES (86,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12237,2,12237,0,96,0,0,0);
INSERT INTO `shop` VALUES (87,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12238,2,12238,0,96,0,0,0);
INSERT INTO `shop` VALUES (88,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12239,0,12239,0,96,0,0,0);
INSERT INTO `shop` VALUES (89,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12240,0,12240,0,96,0,0,0);
INSERT INTO `shop` VALUES (90,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12253,2,12253,0,96,0,0,0);
INSERT INTO `shop` VALUES (91,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12254,2,12254,0,96,0,0,0);
INSERT INTO `shop` VALUES (92,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12256,2,12256,0,96,0,0,0);
INSERT INTO `shop` VALUES (93,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12257,2,12257,0,96,0,0,0);
INSERT INTO `shop` VALUES (94,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12272,2,12272,0,96,0,0,0);
INSERT INTO `shop` VALUES (95,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12275,2,12275,0,96,0,0,0);
INSERT INTO `shop` VALUES (96,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12276,2,12276,0,96,0,0,0);
INSERT INTO `shop` VALUES (97,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12278,0,12278,0,96,0,0,0);
INSERT INTO `shop` VALUES (98,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12279,2,12279,0,96,0,0,0);
INSERT INTO `shop` VALUES (99,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12292,2,12292,0,96,0,0,0);
INSERT INTO `shop` VALUES (100,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12293,2,12293,0,96,0,0,0);
INSERT INTO `shop` VALUES (101,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12294,2,12294,0,96,0,0,0);
INSERT INTO `shop` VALUES (102,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12295,2,12295,0,96,0,0,0);
INSERT INTO `shop` VALUES (103,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,12298,2,12298,0,96,0,0,0);
INSERT INTO `shop` VALUES (104,1.15,0.75,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,552,0,572,0,96,0,0,0);
INSERT INTO `shop` VALUES (105,1.15,0.75,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8703,0,7805,0,96,0,0,0);
INSERT INTO `shop` VALUES (106,1.05,0.95,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,24418,0,24442,0,96,0,0,0);
INSERT INTO `shop` VALUES (107,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,471,0,472,0,96,0,0,0);
INSERT INTO `shop` VALUES (108,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,27806,0,27899,0,96,0,0,0);
INSERT INTO `shop` VALUES (109,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey, I don\'t buy stuff.','I don\'t buy stuff!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,13746,0,15345,0,96,0,0,0);
INSERT INTO `shop` VALUES (110,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31760,0,31788,0,96,0,0,0);
INSERT INTO `shop` VALUES (111,1.2,0.8,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3864,0,3864,0,96,0,0,0);
INSERT INTO `shop` VALUES (112,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,593,0,579,0,96,0,0,0);
INSERT INTO `shop` VALUES (113,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,628,0,628,0,96,0,0,0);
INSERT INTO `shop` VALUES (114,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,634,0,634,0,96,0,0,0);
INSERT INTO `shop` VALUES (115,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,610,0,610,0,96,0,0,0);
INSERT INTO `shop` VALUES (116,1,0.4,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,608,0,2366,0,96,0,0,0);
INSERT INTO `shop` VALUES (117,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,627,0,627,0,96,0,0,0);
INSERT INTO `shop` VALUES (118,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  I don\'t deal in these!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,616,0,616,0,96,0,0,0);
INSERT INTO `shop` VALUES (119,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,647,0,647,0,96,0,0,0);
INSERT INTO `shop` VALUES (120,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,633,0,633,0,96,0,0,0);
INSERT INTO `shop` VALUES (121,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,648,0,648,0,96,0,0,0);
INSERT INTO `shop` VALUES (122,1.05,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','I only buy casino chips.','It appears the casino is a little down on it\'s luck today.  I don\'t have enough reserve cash for that.','You don\'t have the required funds for these chips.','That\'ll be %d talens.  Good luck!','Here is your %d talens.',2,1,2350,0,2353,0,96,0,0,0);
INSERT INTO `shop` VALUES (123,1,0.25,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31769,0,31756,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (124,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,649,0,600,0,96,0,0,0);
INSERT INTO `shop` VALUES (125,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4507,0,4507,0,96,0,0,0);
INSERT INTO `shop` VALUES (126,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,33294,0,33294,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (127,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,168,2,409,0,96,0,0,1);
INSERT INTO `shop` VALUES (128,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1345,2,1345,0,96,0,0,1);
INSERT INTO `shop` VALUES (129,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8737,2,8737,0,96,0,0,1);
INSERT INTO `shop` VALUES (130,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3774,2,3774,0,96,0,0,1);
INSERT INTO `shop` VALUES (131,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,23638,2,23799,0,96,0,0,1);
INSERT INTO `shop` VALUES (132,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25529,2,25593,0,96,0,0,1);
INSERT INTO `shop` VALUES (133,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,30710,2,30703,0,96,0,0,1);
INSERT INTO `shop` VALUES (134,1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,7008,2,7110,0,96,0,0,0);
INSERT INTO `shop` VALUES (135,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,604,0,604,0,96,0,0,0);
INSERT INTO `shop` VALUES (136,0.1,0.05,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31764,2,31759,0,96,0,0,0);
INSERT INTO `shop` VALUES (137,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,607,0,607,0,96,0,0,0);
INSERT INTO `shop` VALUES (138,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4537,0,4537,0,96,0,0,0);
INSERT INTO `shop` VALUES (139,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,630,0,630,0,96,0,0,0);
INSERT INTO `shop` VALUES (140,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1295,0,1295,0,96,0,0,0);
INSERT INTO `shop` VALUES (141,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3755,0,3755,0,96,0,0,0);
INSERT INTO `shop` VALUES (142,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8756,0,8756,0,96,0,0,0);
INSERT INTO `shop` VALUES (143,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,613,0,613,0,96,0,0,0);
INSERT INTO `shop` VALUES (144,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,140,0,419,0,96,0,0,1);
INSERT INTO `shop` VALUES (145,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16200,0,16200,0,96,0,0,1);
INSERT INTO `shop` VALUES (146,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3750,0,3753,0,96,0,0,1);
INSERT INTO `shop` VALUES (147,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1250,0,1352,0,96,0,0,1);
INSERT INTO `shop` VALUES (148,0.8,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31352,0,578,0,96,0,0,1);
INSERT INTO `shop` VALUES (149,1.5,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,147,0,569,0,96,0,0,1);
INSERT INTO `shop` VALUES (150,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,169,0,408,0,96,0,0,1);
INSERT INTO `shop` VALUES (151,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,343,0,775,0,96,0,0,0);
INSERT INTO `shop` VALUES (152,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1347,0,1347,0,96,0,0,1);
INSERT INTO `shop` VALUES (153,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3754,0,3754,0,96,0,0,1);
INSERT INTO `shop` VALUES (154,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8799,0,8799,0,96,0,0,1);
INSERT INTO `shop` VALUES (155,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,23639,0,23798,0,96,0,0,1);
INSERT INTO `shop` VALUES (156,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,340,0,1394,0,96,0,0,0);
INSERT INTO `shop` VALUES (157,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,341,0,3863,0,96,0,0,0);
INSERT INTO `shop` VALUES (158,1,0.1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,342,0,2989,0,96,0,0,0);
INSERT INTO `shop` VALUES (159,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,596,0,583,0,96,0,0,0);
INSERT INTO `shop` VALUES (160,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31767,0,31757,0,96,0,0,0);
INSERT INTO `shop` VALUES (161,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,406,0,406,0,96,0,0,1);
INSERT INTO `shop` VALUES (162,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1388,0,1388,0,96,0,0,1);
INSERT INTO `shop` VALUES (163,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8857,0,8857,0,96,0,0,1);
INSERT INTO `shop` VALUES (164,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,166,0,564,0,96,0,0,0);
INSERT INTO `shop` VALUES (165,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1209,0,1364,0,96,0,0,0);
INSERT INTO `shop` VALUES (166,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3707,0,3737,0,96,0,0,0);
INSERT INTO `shop` VALUES (167,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8701,0,8804,0,96,0,0,0);
INSERT INTO `shop` VALUES (168,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16702,0,16705,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (169,0.05,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8770,0,8770,0,96,0,0,0);
INSERT INTO `shop` VALUES (170,0.05,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3865,0,3865,0,96,0,0,0);
INSERT INTO `shop` VALUES (171,0.05,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1398,0,1398,0,96,0,0,0);
INSERT INTO `shop` VALUES (172,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3866,0,3866,0,96,0,0,0);
INSERT INTO `shop` VALUES (173,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3869,0,3869,0,96,0,0,0);
INSERT INTO `shop` VALUES (174,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35412,0,35463,0,96,0,0,0);
INSERT INTO `shop` VALUES (175,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35414,0,35466,0,96,0,0,0);
INSERT INTO `shop` VALUES (176,1.05,0.95,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35417,0,35470,0,96,0,0,0);
INSERT INTO `shop` VALUES (177,1.4,0.6,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35422,0,35476,0,96,0,0,0);
INSERT INTO `shop` VALUES (178,1.4,0.6,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35423,0,35491,0,96,0,0,0);
INSERT INTO `shop` VALUES (179,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35425,0,35495,0,96,0,0,0);
INSERT INTO `shop` VALUES (180,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35426,0,35494,0,96,0,0,0);
INSERT INTO `shop` VALUES (181,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','I only buy light!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35433,0,35496,0,96,0,0,0);
INSERT INTO `shop` VALUES (182,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','I won\'t buy that!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8848,0,8848,0,96,0,0,0);
INSERT INTO `shop` VALUES (183,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I ain\'t never heard of that!','Hell no, I ain\'t gonna buy that!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Now git the hell outta here!','Here is your %d talens.  Now git the hell outta here!',2,1,18729,0,18729,0,96,0,0,0);
INSERT INTO `shop` VALUES (184,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,611,0,608,0,96,0,0,0);
INSERT INTO `shop` VALUES (185,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31484,0,31492,0,96,0,0,1);
INSERT INTO `shop` VALUES (186,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,164,0,557,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (187,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35432,0,35460,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (188,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,18726,0,18730,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (189,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,35450,0,9723,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (190,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4470,0,4626,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (191,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,594,0,4470,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (192,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,595,0,637,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (193,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,2355,0,2364,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (194,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,33961,0,449,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (195,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,9121,0,9121,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (196,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3871,0,3871,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (197,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3872,0,3872,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (198,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,25527,0,25587,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (199,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,24442,0,24435,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (200,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,23634,0,23662,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (201,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14323,0,14379,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (202,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,14184,0,14184,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (203,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,11032,0,11040,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (204,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,10615,0,10643,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (205,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8766,0,8766,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (206,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,7001,0,7050,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (207,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,5715,0,5766,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (208,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3771,0,3771,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (209,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,2124,0,2218,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (210,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1333,0,1333,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (211,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,597,0,582,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (212,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,598,0,619,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (213,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,599,0,1177,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (214,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  I don\'t deal in these!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4614,0,4614,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (215,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,4612,0,4612,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (216,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3768,0,3768,0,96,0,0,0);
INSERT INTO `shop` VALUES (217,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,3742,0,3742,0,96,0,0,0);
INSERT INTO `shop` VALUES (218,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,36931,0,36931,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (219,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,36937,0,36937,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (220,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,36932,0,36932,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (221,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,36938,0,36938,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (222,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,33291,0,33291,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (223,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,33550,0,33565,0,96,0,0,0);
INSERT INTO `shop` VALUES (224,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,36941,0,36941,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (225,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16704,0,16707,0,96,0,0,0);
INSERT INTO `shop` VALUES (226,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,1394,0,1399,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (227,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,26880,0,26880,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (228,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,26881,0,26881,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (229,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,26882,0,26882,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (230,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,26879,0,26879,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (231,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,9725,0,9725,0,96,0,0,0);
INSERT INTO `shop` VALUES (232,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6420,0,6405,0,96,0,0,0);
INSERT INTO `shop` VALUES (233,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6421,0,6406,0,96,0,0,0);
INSERT INTO `shop` VALUES (234,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6422,0,6407,0,96,0,0,0);
INSERT INTO `shop` VALUES (235,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6423,0,6408,0,96,0,0,0);
INSERT INTO `shop` VALUES (236,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6433,0,6418,0,96,0,0,0);
INSERT INTO `shop` VALUES (237,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6434,0,6419,0,96,0,0,0);
INSERT INTO `shop` VALUES (238,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6435,0,6420,0,96,0,0,0);
INSERT INTO `shop` VALUES (239,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6436,0,6421,0,96,0,0,0);
INSERT INTO `shop` VALUES (240,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6425,0,6410,0,96,0,0,0);
INSERT INTO `shop` VALUES (241,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6437,0,6422,0,96,0,0,0);
INSERT INTO `shop` VALUES (242,1,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6438,0,6423,0,96,0,0,0);
INSERT INTO `shop` VALUES (243,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6472,0,6470,0,96,0,0,0);
INSERT INTO `shop` VALUES (244,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6471,0,6469,0,96,0,0,0);
INSERT INTO `shop` VALUES (245,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16700,0,16700,0,96,0,0,0);
INSERT INTO `shop` VALUES (246,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16701,0,16702,0,96,0,0,0);
INSERT INTO `shop` VALUES (247,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,6466,0,6463,0,96,0,0,0);
INSERT INTO `shop` VALUES (248,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16703,0,16706,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (249,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,44845,0,44853,0,96,0,0,0);
INSERT INTO `shop` VALUES (250,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,8876,0,33270,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (251,1.05,0.5,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,31906,0,31906,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (252,1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,614,0,585,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (253,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,45054,0,45054,0,96,0,0,0);
INSERT INTO `shop` VALUES (254,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16705,0,16708,0,96,0,0,0);
INSERT INTO `shop` VALUES (255,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,15380,0,15380,0,96,0,0,0);
INSERT INTO `shop` VALUES (256,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Hey!  What kind of clothing is this?!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,15376,0,15375,0,96,0,0,0);
INSERT INTO `shop` VALUES (257,1.1,0.9,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Armor is all I care about!','I can\'t afford that!','If you can\'t afford it, don\'t ask for it!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,15378,0,15378,0,96,0,0,0);
INSERT INTO `shop` VALUES (258,1.1,1,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,15379,0,15379,0,96,0,0,0);
INSERT INTO `shop` VALUES (259,0,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16706,0,16709,0,96,0,0,NULL);
INSERT INTO `shop` VALUES (260,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16707,0,16711,0,96,0,0,0);
INSERT INTO `shop` VALUES (261,1,0,'I don\'t have that right now.  Try \"list\".','I\'ve never heard of that!','Go sell it to someone who cares!','I can\'t afford that!','I don\'t think you have that kind of money!','That\'ll be %d talens.  Thank you!','Here is your %d talens.  Thank you!',2,1,16708,0,16712,0,96,0,0,0);
/*!40000 ALTER TABLE `shop` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2019-05-02 21:42:48
